site_name: Deltas-Docs-Rewrites
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Command-Based:
    - Getting Started: command-based/getting-started.md
  - System Identification:
    - Introduction to System Identification: system-id/system-id.md
